### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by tomory** [preservim/vim-textobj-quote#37]
The Installation section refers to a dependency on "kana/vim-textobject-user". It should instead say "kana/vim-textobj-user".

The link is correct; only the text is wrong. But this is still a problem for those who use package managers that take just the repo name, and who therefore just copy and paste it from the README.

**Comment by telemachus** [comment]
Thanks for reporting this. (What a silly typo: the repo name is immediately after my mistake!) The fix should be merged soon.
